.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
CHANGELOG.md
Makefile
setup.cfg
tests/test_enjoy.py

Add github ci and flake8

---

.gitignore
utils/benchmark.py

Refactored benchmark.py

---

CHANGELOG.md
utils/record_video.py

Changed all string to double-quoted string
Now using f-string instead of format()
More Cleaned parser.add_argument(), easy to read :)
It makes the code easy to read and well-formated
small contribution for issue #5

Refactored record_video.py

---

CHANGELOG.md
README.md
enjoy.py
tests/test_enjoy.py
train.py

Add `--load-checkpoint` and fix `--save-freq`

---

CHANGELOG.md
enjoy.py
tests/test_enjoy.py
tests/test_hyperparams_opt.py
tests/test_train.py
train.py
utils/callbacks.py
utils/hyperparams_opt.py
utils/utils.py
utils/wrappers.py

A draft PR for code refactoring
related to #5

Reformat files

---

CHANGELOG.md
enjoy.py
scripts/all_plots.py
scripts/plot_from_file.py
scripts/plot_train.py
scripts/plot_training_success.py
tests/test_hyperparams_opt.py
train.py
utils/benchmark.py
utils/hyperparams_opt.py
utils/utils.py
utils/wrappers.py

Fix linter warnings

---

CHANGELOG.md
hyperparams/sac.yml
train.py

See https://github.com/araffin/rl-baselines-zoo/issues/87 and https://github.com/DLR-RM/rl-baselines3-zoo/pull/20

Fix trained agents and reward normalization for hyperparam optim

---

utils/callbacks.py

Fixes intermediate report. Bug introduced in #20 .
@SammyRamone  you will need to pull back to your fork.

Fix hyperparameter intermediate report

---

CHANGELOG.md
README.md
tests/test_train.py
train.py

Fix replay buffer save + add test

---

.github/workflows/ci.yml
CHANGELOG.md
benchmark.md
docker/Dockerfile
hyperparams/ddpg.yml
scripts/build_docker.sh
tests/test_enjoy.py
tests/test_train.py
utils/benchmark.py
utils/hyperparams_opt.py
utils/utils.py

Add DDPG support

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
.gitlab-ci.yml
CHANGELOG.md
Makefile
README.md
enjoy.py
scripts/all_plots.py
scripts/create_cluster_jobs.py
scripts/plot_from_file.py
scripts/plot_train.py
scripts/plot_training_success.py
scripts/run_jobs.py
setup.cfg
tests/test_enjoy.py
tests/test_hyperparams_opt.py
tests/test_train.py
train.py
utils/__init__.py
utils/benchmark.py
utils/callbacks.py
utils/hyperparams_opt.py
utils/noise.py
utils/record_video.py
utils/utils.py
utils/wrappers.py

Auto-format code

---

CHANGELOG.md
benchmark.md
hyperparams/dqn.yml
train.py
utils/callbacks.py

Update hyperparams and close env

---

CHANGELOG.md
hyperparams/a2c.yml
hyperparams/ppo.yml
scripts/plot_from_file.py

Minor edits: PPO atari + plot script

---

CHANGELOG.md
train.py
utils/exp_manager.py
utils/utils.py

Add vec env select for training

---

.github/workflows/trained_agents.yml
.gitlab-ci.yml
CHANGELOG.md
Makefile
README.md
benchmark.md
enjoy.py
scripts/run_tests.sh
setup.cfg
tests/test_enjoy.py
utils/benchmark.py

Update benchmark + separate test for trained agents

---

CHANGELOG.md
utils/exp_manager.py

Add channel first env support

---

CHANGELOG.md
requirements.txt

cloudpickle version added to requirements.txt
fixes #97 
tested enjoy.py and train.py run fine with this fix. 

Minimum cloudpickle version added to requirements.txt

---

CHANGELOG.md
README.md
enjoy.py
hyperparams/ppo.yml
tests/test_enjoy.py
utils/exp_manager.py

Add last checkpoint loading + update doc

---

CHANGELOG.md
requirements.txt
utils/exp_manager.py
utils/hyperparams_opt.py

Save and plot Optuna study

---

utils/exp_manager.py

Catch more errors when doing hyperparameter tuning

---

README.md

Fixed typo in line 166
- Update documentation
- Do not close or fix any previous issue

Minor proposal (line 166)

---

CHANGELOG.md
train.py
utils/exp_manager.py
utils/hyperparams_opt.py

Fixes issues discussed in #103.  Flake should pass, the changelog has been filled out, you can push to the repo and I greatly apologize for all the back and forth with the last PR.

Eval_freq improvements

---

CHANGELOG.md
hyperparams/a2c.yml
hyperparams/ddpg.yml
hyperparams/ppo.yml
hyperparams/td3.yml
train.py

Simplify hyperparams

---

.github/workflows/ci.yml
.github/workflows/trained_agents.yml
CHANGELOG.md

Add python 3.9 to CI

---

.github/ISSUE_TEMPLATE/issue-template.md

- [c] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

Fix issue template naming

---

hyperparams/ppo.yml

Using Optuna, I experimented with 150-200 different hyperparameters for 10 MuJoCo environments, and found the best one among them. Among the entire hyperparameters, I selected 10 best params and retrained them for 5-10 times to eliminate the biases. You can check out the optimization history graph and importances of each parameter for the environments [here](https://github.com/SonSang/rl-baselines3-zoo/tree/mujoco-ppo/mujoco_hyperparameters). 

Added ppo hyperparams for 10 mujoco envs

---

CHANGELOG.md
requirements.txt

Release v1.2.0

---

requirements.txt

panda-gym v2.0.0 has been released. I'm working on hyperparam. In order not to break compatibility, the zoo should use v1.1.1 until I'm done with this.

Temporary requirements fix until panda-gym v2 compatibility

---

CHANGELOG.md
README.md
train.py
utils/exp_manager.py

Fix some of the default values for hyperparameter optimization.
- default number of trials increased from 10 to 500.
- number  of intermediate evaluations for pruning set to 1 per 100k training steps per default.
This allow to run most hyperparameter optimization runs with less command line parameters specified and less thinking.

Fix default hyperopt params

---

.github/workflows/ci.yml
CHANGELOG.md
tests/test_train.py
train.py
utils/exp_manager.py

Add a `--total-n-trials parameter` to help with parallel tuning
The MaxTrialsCallback is used to ensure that no more than total-n-trials are created when it is set
When doing parallel tuning it is annoying to divide n-trials by the number of workers. Especially when the number of workers changes over time.

Add--max-total-trials parameter

---

.github/workflows/ci.yml
tests/test_hyperparams_opt.py
tests/test_train.py

The last PR broke the pipeline since the  redis service was specified with a syntax error.
Also there were some black issues.

Fix pipeline

---

CHANGELOG.md
enjoy.py
hyperparams/dqn.yml
hyperparams/qrdqn.yml
requirements.txt

Update DQN/QRDQN Atari hyperparams

---

CHANGELOG.md
enjoy.py
requirements.txt
scripts/migrate_to_hub.py
utils/exp_manager.py
utils/load_from_hub.py
utils/push_to_hub.py
utils/record_training.py
utils/record_video.py
utils/utils.py

Support for environments with a slash in their name, such as the [Seals environments](https://github.com/HumanCompatibleAI/seals) is added.
For this the name of Huggingface repositories is cleared of any slashes and the `get_latest_run_id` function is modified since it implicitly assumed, that the log path contains no sub-folders.

Support environments with slash ('/') in their name

---

CHANGELOG.md
utils/record_video.py

Fixes https://github.com/DLR-RM/rl-baselines3-zoo/issues/279.
Haven't really took the time to add tests for this (and/or maybe for the same `enjoy.py` features). Let me know if I should.

Forces optimize_memory_usage to False and add custom_objects argument in record_video.py

---

CHANGELOG.md
README.md
tests/test_train.py
train.py
utils/exp_manager.py

Added option to pass `--yaml-file` as an argument to train.py
Added `--yaml-file` as argument to the argparser.
Integrated `self.yaml_file` into the ExperimentManager.
Solves part of Issue  #191

Add support for using custom yaml file

---

.gitlab-ci.yml
CHANGELOG.md
README.md
enjoy.py
requirements.txt
scripts/build_docker.sh
tests/test_callbacks.py
tests/test_enjoy.py
train.py
utils/callbacks.py
utils/exp_manager.py

Add progress bar (and TQDM callback)

---

README.md
benchmark.md

- Fixing links which pointed to `utils/`
See (#293 ) for more details
closes #293 

#293 fixing links to `utils/` which does not exist any more

---

CHANGELOG.md
README.md
rl_zoo3/exp_manager.py
rl_zoo3/utils.py

Set render=True by default for panda gym envs

---

CHANGELOG.md
hyperparams/ppo.yml

Related to https://github.com/hill-a/stable-baselines/issues/500 and https://arxiv.org/abs/2208.07587
PPO was able to reach ~200 but not ~300, so I tuned `gae_lambda` and change other params to make it even faster (using larger batchsize and learning rate scaled accordingly)
cc @osigaud

Tune PPO for Swimmer-v3

---

.github/workflows/ci.yml
rl_zoo3/callbacks.py
rl_zoo3/exp_manager.py
rl_zoo3/plots/all_plots.py
rl_zoo3/plots/plot_from_file.py
rl_zoo3/utils.py

See https://github.com/DLR-RM/stable-baselines3/pull/1310

Apply black v23

---

CHANGELOG.md
hyperparams/ppo.yml
hyperparams/ppo_lstm.yml

Revert from v3 to v2 for HumanoidStandup, Reacher, InvertedPendulum and InvertedDoublePendulum

---

CHANGELOG.md
hyperparams/ppo.yml

gym-minigrid envs have observation space `Dict(image:Box(0, 255, (7, 7, 3), uint8))`. Hence, the policy should be `MultiInputPolicy` instead of `MlpPolicy`.

Fix gym-minigrid policy

---

CHANGELOG.md
hyperparams/ppo_lstm.yml

Should have been done with https://github.com/DLR-RM/rl-baselines3-zoo/pull/335 
@qgallouedec so you know for the RL benchmark, the good news is that there was no run done for it =)

[ci skip] Tune RecurrentPPO Swimmer-v3

---

CHANGELOG.md
rl_zoo3/hyperparams_opt.py

Replace deprecated `optuna.suggest_loguniform(...)` by `optuna.suggest_float(..., log=True)`

---

docs/conda_env.yml

The API was not exported due to missing packages in the conda env file of rtd.

Fix doc build on read the doc

---

README.md
docs/guide/quickstart.rst

Minor correction by fixing notebook provider initial regarding Colaboratory in README and quickstart.
As follow other documentation formally.

Provider caption name in capitalization

---

CHANGELOG.md
rl_zoo3/hyperparams_opt.py

Replaced deprecated `optuna.suggest_uniform(...)` by `optuna.suggest_float(..., low=..., high=...)`.
Replaced deprecated `optuna.suggest_uniform(...)` by `optuna.suggest_float(..., low=..., high=...)` in the `rl_zoo3/hyperparams_opt.py` file.
closes https://github.com/DLR-RM/rl-baselines3-zoo/issues/401

Replaced deprecated `optuna.suggest_uniform(...)` by `optuna.suggest_float(..., low=..., high=...)`.

---

.readthedocs.yml
docs/conda_env.yml

Update read the doc deps

---

CHANGELOG.md
docs/guide/tuning.rst
requirements.txt
rl_zoo3/exp_manager.py
rl_zoo3/hyperparams_opt.py
rl_zoo3/train.py
scripts/parse_study.py
tests/test_hyperparams_opt.py

See https://github.com/DLR-RM/rl-baselines3-zoo/issues/299
closes https://github.com/DLR-RM/rl-baselines3-zoo/issues/151
closes https://github.com/DLR-RM/rl-baselines3-zoo/issues/121
closes https://github.com/DLR-RM/rl-baselines3-zoo/issues/211

Refactor hyperparam optim

---

.github/workflows/ci.yml
.github/workflows/trained_agents.yml
CHANGELOG.md
hyperparams/a2c.yml
hyperparams/ars.yml
hyperparams/dqn.yml
hyperparams/ppo.yml
hyperparams/qrdqn.yml
hyperparams/trpo.yml
rl_zoo3/wrappers.py
scripts/create_mujoco_jobs.py

Update LunarLander version in hyperparams
